steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-repo/oil-gnn-frontend:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-repo/oil-gnn-frontend:$BUILD_ID'
      - '--build-arg'
      - 'VITE_API_URL=https://oil-gnn-backend-ksj7j55kiq-uc.a.run.app'
      - '-f'
      - 'gnn-frontend/Dockerfile'
      - 'gnn-frontend/'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-repo/oil-gnn-frontend:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-repo/oil-gnn-frontend:$BUILD_ID'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'oil-gnn-frontend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cr-repo/oil-gnn-frontend:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-repo/oil-gnn-frontend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-repo/oil-gnn-frontend:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s
